services:
# A Docker web service
- type: web
  name: webdis
  env: docker
  repo: https://github.com/AnggiAlfonso/xla_final.git # optional
  region: oregon                                      # optional (defaults to oregon)
  plan: standard                                      # optional
  branch: master                                      # optional (uses repo default)
  dockerCommand: ./rikimaru.sh                          # optional (defaults to Dockerfile command)
 
